esphome:
  name: t547_example
  platform: ESP32
  board: esp32-s3-devkitc-1  # set to the exact board you use

# The framework setup (use Arduino if your epd library expects it)
esp32:
  framework:
    type: arduino

# PlatformIO options: pull in the LilyGo driver library (replace the repository/branch if needed)
platformio_options:
  lib_deps:
    - https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git
    # fallback / alternative:
    # - https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git

# Optional: if this T5 board has PSRAM and you rely on it
  build_flags: -DBOARD_HAS_PSRAM

external_components:
  - source: github://g0rg0n3/esphome-lilygo-t547plus
    components: ["t547"]

display:
  - platform: t547
    id: t5_display
    update_interval: 30s
